row = $('.row').not('[id]').eq(1)
row.attr('id', 'recipe-<%= @recipe.id %>')
row.find('[data-method="delete"]').attr('href', '<%= recipe_path(@recipe) %>').removeClass('hide')
row.find('[data-method="delete"]').prev().attr('href', '<%= recipe_products_recipes_path(@recipe) %>').removeClass('hide')
form = row.find('form')
form.attr('action', '<%= recipe_path(@recipe) %>')
form.attr('method', 'put')
form.data('waiting-response', false)
$('h1 .badge').replaceWith('<%= last_updated([@recipe]) %>')
if row.siblings('.row').not('[id]').length == 1
  newRow = row.clone().appendTo(row.parent())
  newRow.find('.select2-container').remove()
  newRow.find('input').not('[type="checkbox"]').val('')
  newRow.find('input').filter('[type="checkbox"]').attr('checked', false)
  $.each newRow.find('[data-source]'), ->
    initSelect2 $(this)
  newRow.removeAttr('id')
  newRow.find('[data-method="delete"]').addClass('hide')
  newRow.find('[data-method="delete"]').prev().addClass('hide')
  newForm = newRow.find('form')
  newForm.attr('action', '<%= recipes_path %>')
  newForm.attr('method', 'post')
