row = $('.row').not('[id]').eq(1)
row.attr('id', 'shopping_list-<%= @shopping_list.id %>')
row.find('[data-method="delete"]').attr('href', '<%= shopping_list_path(@shopping_list) %>').removeClass('hide')
row.find('[data-method="delete"]').prev().attr('href', '<%= shopping_list_shopping_list_items_path(@shopping_list) %>').removeClass('hide')
form = row.find('form')
form.attr('action', '<%= shopping_list_path(@shopping_list) %>')
form.attr('method', 'put')
form.data('waiting-response', false)
$('h1 .badge').replaceWith('<%= last_updated([@shopping_list]) %>')
if row.siblings('.row').not('[id]').length == 1
  newRow = row.clone().appendTo(row.parent())
  newRow.find('.select2-container').remove()
  newRow.find('input').not('[type="checkbox"]').val('')
  newRow.find('input').filter('[type="checkbox"]').attr('checked', false)
  $.each newRow.find('[data-source]'), ->
    initSelect2 $(this)
  newRow.removeAttr('id')
  newRow.find('[data-method="delete"]').addClass('hide')
  newRow.find('[data-method="delete"]').prev().addClass('hide')
  newForm = newRow.find('form')
  newForm.attr('action', '<%= shopping_lists_path %>')
  newForm.attr('method', 'post')
