row = $('.row').not('[id]').eq(1)
row.attr('id', 'category-<%= @category.id %>')
row.find('[data-method="delete"]').attr('href', '<%= category_path(@category) %>').removeClass('hide')
form = row.find('form')
form.attr('action', '<%= category_path(@category) %>')
form.attr('method', 'put')
form.data('waiting-response', false)
if row.siblings('.row').not('[id]').length == 1
  newRow = row.clone().appendTo(row.parent())
  newRow.find('.select2-container').remove()
  newRow.find('input').val('')
  $.each newRow.find('[data-source]'), ->
    initSelect2 $(this)
  newRow.removeAttr('id')
  newForm = newRow.find('form')
  newForm.attr('action', '<%= categories_path %>')
  newForm.attr('method', 'post')
